language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
services:
  - memcached
  - redis
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf libmemcached-dev libcurl4-openssl-dev libhiredis-dev libmarkdown2-dev libcgroup-dev libcap-dev iproute-dev
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mrbgem_test_ci/.travis_build_config.rb build_config.rb
script: 
  - make all test
notifications:
  webhooks:
    - secure: "UDjzP3coFurYEPXo7IsgjisSWmjGC+BPbja6LTvMPwY+t6ZKERxrp3viDc/kPXDNlGBFXP7K2bu+UefukJIWUuctSoTt6CVLGqdegwzY5zFtlaCfKsxd/OxIO91QqmPwYW4UeSkOdReejUhncZYZ1/dYjJszVNgi2uMb2X4ZQ2M="

