language: c
compiler:
  - gcc
  - clang
services:
  - memcached
  - redis
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf libmemcached-dev
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mrbgem_test_ci/.travis_build_config.rb build_config.rb
script: 
  - make all test
